// Generated by scripts/generate_contract_docs.py; do not edit.
export interface Node {
  id: string;
  label: string;
  kind: string;
  x: number;
  y: number;
}

export interface Link {
  id: string;
  from_node: string;
  to_node: string;
  length_m: number;
  lanes: number;
  storage_capacity_veh: number;
  free_flow_speed_kph: number;
}

export interface Movement {
  id: string;
  node_id: string;
  incoming_link_id: string;
  outgoing_link_id: string;
  turning_ratio: number;
}

export interface SignalPhase {
  id: string;
  node_id: string;
  movement_ids: string[];
  min_green_s: number;
  max_green_s: number;
  amber_s: number;
  all_red_s: number;
}

export interface MovementState {
  movement_id: string;
  queue_veh: number;
  arrival_rate_vpm: number;
  departure_rate_vpm: number;
  avg_speed_kph: number;
  occupancy_ratio: number;
  downstream_capacity_veh: number;
  current_phase_id: string;
  waiting_age_s: number;
  vehicle_count: number;
  arrivals_total: number;
  departures_total: number;
  permission: string;
}

export interface TrafficState {
  schema_version: "1.0";
  run_id: string;
  timestamp: string;
  simulation_time_s: number;
  source: string;
  movements: MovementState[];
  signals: SignalState[];
  vehicles_in_network: number;
  inserted_total: number;
  arrived_total: number;
  teleported_total: number;
  scenario_type: string;
  seed: number;
}

export interface Forecast {
  id: string;
  run_id: string;
  movement_id: string;
  horizon_s: number;
  queue_veh: number;
  occupancy_ratio: number;
  arrivals_veh: number;
  risk: string;
  spillback_eta_s?: number;
  model_version: string;
  explanation_facts: string[];
}

export interface TimingChange {
  node_id: string;
  phase_id: string;
  green_s: number;
}

export interface Recommendation {
  id: string;
  run_id: string;
  timestamp: string;
  priority: string;
  reason: string;
  changes: TimingChange[];
  safety_status: string;
  status: string;
  explanation_facts: string[];
}

export interface OperatorAction {
  id: string;
  run_id: string;
  actor: string;
  recommendation_id: string;
  action: string;
  reason: string;
  timestamp: string;
  modifications: TimingChange[];
}

export interface Incident {
  id: string;
  run_id: string;
  node_id: string;
  kind: string;
  capacity_ratio: number;
  status: string;
}

export interface EmergencyEvent {
  id: string;
  run_id: string;
  route_node_ids: string[];
  status: string;
  eta_s: number[];
}

export interface ComponentHealth {
  component: string;
  status: string;
  message: string;
}

export interface HealthState {
  timestamp: string;
  components: ComponentHealth[];
}

export interface AuditEvent {
  id: string;
  run_id: string;
  timestamp: string;
  actor: string;
  recommendation_id: string;
  event_type: string;
  before: TimingChange[];
  after: TimingChange[];
  reason: string;
  safety_result: string;
}

export interface Alert {
  id: string;
  run_id: string;
  severity: string;
  target_id: string;
  message: string;
}

export interface SignalState {
  node_id: string;
  phase_id: string;
  indication: string;
  remaining_s: number;
  permitted_movement_ids: string[];
}

export interface ComparisonResult {
  run_id: string;
  recommendation_id: string;
  baseline_max_queue_veh: number;
  candidate_max_queue_veh: number;
  baseline_avg_delay_s: number;
  candidate_avg_delay_s: number;
}

export interface EventEnvelope {
  schema_version: "1.0";
  sequence: string;
  timestamp: string;
  network_state?: TrafficState;
  junction_state?: SignalState;
  forecast_updated?: Forecast;
  recommendation_created?: Recommendation;
  recommendation_updated?: Recommendation;
  incident_updated?: Incident;
  emergency_updated?: EmergencyEvent;
  health_updated?: HealthState;
  audit_appended?: AuditEvent;
}

export interface RunCommand {
  schema_version: "1.0";
  scenario_type: string;
  seed: number;
  mode: string;
  run_id: string;
}

export interface RunRequest {
  run_id: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
}

export type LiveEvent =
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "network.state"; payload: TrafficState } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "junction.state"; payload: SignalState } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "forecast.updated"; payload: Forecast } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "recommendation.created"; payload: Recommendation } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "recommendation.updated"; payload: Recommendation } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "incident.updated"; payload: Incident } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "emergency.updated"; payload: EmergencyEvent } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "health.updated"; payload: HealthState } |
  { schema_version: "1.0"; sequence: string; timestamp: string; type: "audit.appended"; payload: AuditEvent };
