// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: foundation.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateRun = `-- name: ActivateRun :one
UPDATE scenario_runs SET status='running' WHERE id=$1 AND status='prepared' RETURNING id, config_id, scenario_type, seed, mode, status, started_at, ended_at, demand_source
`

func (q *Queries) ActivateRun(ctx context.Context, id pgtype.UUID) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, activateRun, id)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ConfigID,
		&i.ScenarioType,
		&i.Seed,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.DemandSource,
	)
	return i, err
}

const appendAudit = `-- name: AppendAudit :one
INSERT INTO audit_events (id,run_id,recommendation_id,actor,event_type,before_values,after_values,reason,safety_result) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING sequence, id, run_id, recommendation_id, actor, event_type, before_values, after_values, reason, safety_result, created_at
`

type AppendAuditParams struct {
	ID               pgtype.UUID     `json:"id"`
	RunID            pgtype.UUID     `json:"run_id"`
	RecommendationID pgtype.UUID     `json:"recommendation_id"`
	Actor            string          `json:"actor"`
	EventType        string          `json:"event_type"`
	BeforeValues     json.RawMessage `json:"before_values"`
	AfterValues      json.RawMessage `json:"after_values"`
	Reason           string          `json:"reason"`
	SafetyResult     string          `json:"safety_result"`
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAudit,
		arg.ID,
		arg.RunID,
		arg.RecommendationID,
		arg.Actor,
		arg.EventType,
		arg.BeforeValues,
		arg.AfterValues,
		arg.Reason,
		arg.SafetyResult,
	)
	var i AuditEvent
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.RunID,
		&i.RecommendationID,
		&i.Actor,
		&i.EventType,
		&i.BeforeValues,
		&i.AfterValues,
		&i.Reason,
		&i.SafetyResult,
		&i.CreatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO scenario_runs (id,config_id,scenario_type,seed,mode,status,demand_source) VALUES ($1,$2,$3,$4,$5,'prepared',$6) RETURNING id, config_id, scenario_type, seed, mode, status, started_at, ended_at, demand_source
`

type CreateRunParams struct {
	ID           pgtype.UUID `json:"id"`
	ConfigID     string      `json:"config_id"`
	ScenarioType string      `json:"scenario_type"`
	Seed         int64       `json:"seed"`
	Mode         string      `json:"mode"`
	DemandSource string      `json:"demand_source"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.ConfigID,
		arg.ScenarioType,
		arg.Seed,
		arg.Mode,
		arg.DemandSource,
	)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ConfigID,
		&i.ScenarioType,
		&i.Seed,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.DemandSource,
	)
	return i, err
}

const endRunningRuns = `-- name: EndRunningRuns :exec
UPDATE scenario_runs SET status='ended',ended_at=now() WHERE status='running'
`

func (q *Queries) EndRunningRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, endRunningRuns)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT id, schema_version, config, created_at FROM network_configs WHERE id=$1
`

func (q *Queries) GetConfig(ctx context.Context, id string) (NetworkConfig, error) {
	row := q.db.QueryRow(ctx, getConfig, id)
	var i NetworkConfig
	err := row.Scan(
		&i.ID,
		&i.SchemaVersion,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, config_id, scenario_type, seed, mode, status, started_at, ended_at, demand_source FROM scenario_runs WHERE id=$1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ConfigID,
		&i.ScenarioType,
		&i.Seed,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.DemandSource,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT sequence, id, run_id, recommendation_id, actor, event_type, before_values, after_values, reason, safety_result, created_at FROM audit_events WHERE sequence > $1 ORDER BY sequence ASC LIMIT $2
`

type ListAuditParams struct {
	Sequence int64 `json:"sequence"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.ID,
			&i.RunID,
			&i.RecommendationID,
			&i.Actor,
			&i.EventType,
			&i.BeforeValues,
			&i.AfterValues,
			&i.Reason,
			&i.SafetyResult,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, config_id, scenario_type, seed, mode, status, started_at, ended_at, demand_source FROM scenario_runs ORDER BY started_at DESC,id DESC LIMIT $1
`

func (q *Queries) ListRuns(ctx context.Context, limit int32) ([]ScenarioRun, error) {
	rows, err := q.db.Query(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScenarioRun{}
	for rows.Next() {
		var i ScenarioRun
		if err := rows.Scan(
			&i.ID,
			&i.ConfigID,
			&i.ScenarioType,
			&i.Seed,
			&i.Mode,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.DemandSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAggregate = `-- name: SaveAggregate :exec
INSERT INTO traffic_state_snapshots(id,run_id,window_start,window_s,aggregate) VALUES ($1,$2,$3,$4,$5)
`

type SaveAggregateParams struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowS     int32              `json:"window_s"`
	Aggregate   json.RawMessage    `json:"aggregate"`
}

func (q *Queries) SaveAggregate(ctx context.Context, arg SaveAggregateParams) error {
	_, err := q.db.Exec(ctx, saveAggregate,
		arg.ID,
		arg.RunID,
		arg.WindowStart,
		arg.WindowS,
		arg.Aggregate,
	)
	return err
}

const saveConfig = `-- name: SaveConfig :exec
INSERT INTO network_configs (id, schema_version, config) VALUES ($1,$2,$3) ON CONFLICT(id) DO NOTHING
`

type SaveConfigParams struct {
	ID            string          `json:"id"`
	SchemaVersion string          `json:"schema_version"`
	Config        json.RawMessage `json:"config"`
}

func (q *Queries) SaveConfig(ctx context.Context, arg SaveConfigParams) error {
	_, err := q.db.Exec(ctx, saveConfig, arg.ID, arg.SchemaVersion, arg.Config)
	return err
}

const saveEmergency = `-- name: SaveEmergency :exec
INSERT INTO emergencies(id,run_id,status,payload) VALUES ($1,$2,$3,$4)
`

type SaveEmergencyParams struct {
	ID      pgtype.UUID     `json:"id"`
	RunID   pgtype.UUID     `json:"run_id"`
	Status  string          `json:"status"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) SaveEmergency(ctx context.Context, arg SaveEmergencyParams) error {
	_, err := q.db.Exec(ctx, saveEmergency,
		arg.ID,
		arg.RunID,
		arg.Status,
		arg.Payload,
	)
	return err
}

const saveHealthEvent = `-- name: SaveHealthEvent :exec
INSERT INTO system_health_events(id,component,status,details) VALUES ($1,$2,$3,$4)
`

type SaveHealthEventParams struct {
	ID        pgtype.UUID     `json:"id"`
	Component string          `json:"component"`
	Status    string          `json:"status"`
	Details   json.RawMessage `json:"details"`
}

func (q *Queries) SaveHealthEvent(ctx context.Context, arg SaveHealthEventParams) error {
	_, err := q.db.Exec(ctx, saveHealthEvent,
		arg.ID,
		arg.Component,
		arg.Status,
		arg.Details,
	)
	return err
}

const saveIncident = `-- name: SaveIncident :exec
INSERT INTO incidents(id,run_id,node_id,capacity_ratio,status,payload) VALUES ($1,$2,$3,$4,$5,$6)
`

type SaveIncidentParams struct {
	ID            pgtype.UUID     `json:"id"`
	RunID         pgtype.UUID     `json:"run_id"`
	NodeID        string          `json:"node_id"`
	CapacityRatio float64         `json:"capacity_ratio"`
	Status        string          `json:"status"`
	Payload       json.RawMessage `json:"payload"`
}

func (q *Queries) SaveIncident(ctx context.Context, arg SaveIncidentParams) error {
	_, err := q.db.Exec(ctx, saveIncident,
		arg.ID,
		arg.RunID,
		arg.NodeID,
		arg.CapacityRatio,
		arg.Status,
		arg.Payload,
	)
	return err
}

const saveOperatorAction = `-- name: SaveOperatorAction :exec
INSERT INTO operator_actions(id,run_id,recommendation_id,actor,action,reason,payload) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type SaveOperatorActionParams struct {
	ID               pgtype.UUID     `json:"id"`
	RunID            pgtype.UUID     `json:"run_id"`
	RecommendationID pgtype.UUID     `json:"recommendation_id"`
	Actor            string          `json:"actor"`
	Action           string          `json:"action"`
	Reason           string          `json:"reason"`
	Payload          json.RawMessage `json:"payload"`
}

func (q *Queries) SaveOperatorAction(ctx context.Context, arg SaveOperatorActionParams) error {
	_, err := q.db.Exec(ctx, saveOperatorAction,
		arg.ID,
		arg.RunID,
		arg.RecommendationID,
		arg.Actor,
		arg.Action,
		arg.Reason,
		arg.Payload,
	)
	return err
}

const saveRecommendation = `-- name: SaveRecommendation :exec
INSERT INTO recommendations (id,run_id,status,payload) VALUES ($1,$2,$3,$4)
`

type SaveRecommendationParams struct {
	ID      pgtype.UUID     `json:"id"`
	RunID   pgtype.UUID     `json:"run_id"`
	Status  string          `json:"status"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) SaveRecommendation(ctx context.Context, arg SaveRecommendationParams) error {
	_, err := q.db.Exec(ctx, saveRecommendation,
		arg.ID,
		arg.RunID,
		arg.Status,
		arg.Payload,
	)
	return err
}
