// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	Sequence         int64              `json:"sequence"`
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	RecommendationID pgtype.UUID        `json:"recommendation_id"`
	Actor            string             `json:"actor"`
	EventType        string             `json:"event_type"`
	BeforeValues     json.RawMessage    `json:"before_values"`
	AfterValues      json.RawMessage    `json:"after_values"`
	Reason           string             `json:"reason"`
	SafetyResult     string             `json:"safety_result"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Emergency struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Status    string             `json:"status"`
	Payload   json.RawMessage    `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Incident struct {
	ID            pgtype.UUID        `json:"id"`
	RunID         pgtype.UUID        `json:"run_id"`
	NodeID        string             `json:"node_id"`
	CapacityRatio float64            `json:"capacity_ratio"`
	Status        string             `json:"status"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type NetworkConfig struct {
	ID            string             `json:"id"`
	SchemaVersion string             `json:"schema_version"`
	Config        json.RawMessage    `json:"config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OperatorAction struct {
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	RecommendationID pgtype.UUID        `json:"recommendation_id"`
	Actor            string             `json:"actor"`
	Action           string             `json:"action"`
	Reason           string             `json:"reason"`
	Payload          json.RawMessage    `json:"payload"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Recommendation struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Status    string             `json:"status"`
	Payload   json.RawMessage    `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ScenarioRun struct {
	ID           pgtype.UUID        `json:"id"`
	ConfigID     string             `json:"config_id"`
	ScenarioType string             `json:"scenario_type"`
	Seed         int64              `json:"seed"`
	Mode         string             `json:"mode"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
}

type SchemaMigration struct {
	Version   int32              `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type SystemHealthEvent struct {
	ID        pgtype.UUID        `json:"id"`
	Component string             `json:"component"`
	Status    string             `json:"status"`
	Details   json.RawMessage    `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TrafficStateSnapshot struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowS     int32              `json:"window_s"`
	Aggregate   json.RawMessage    `json:"aggregate"`
}
