"use client";
import type { TrafficState } from '../../../packages/contracts/typescript/events';
import type { Network } from '../../../packages/contracts/typescript/network';
export function LiveSummary({live}:{live:{fresh:boolean;frame:TrafficState|null;latency:number;connected:boolean}}){
 const f=live.fresh?live.frame:null;
 return <section className="live-panel" aria-label="Live simulation measurements" data-testid="live-summary">
  <div className="live-heading"><div><span className="overline">LIVE STATE / SYNTHETIC</span><h2>{f ? `${f.scenario_type.replaceAll('_',' ')} · ${f.simulation_time_s}s` : live.frame ? 'Stream stale / disconnected' : 'Waiting for a scenario'}</h2></div><span className="quiet-badge">{f ? `${Math.round(live.latency)} ms delivery` : live.connected ? 'NO FRESH DATA' : 'DISCONNECTED'}</span></div>
  {f ? <><div className="live-metrics"><div><span>IN NETWORK</span><strong>{f.vehicles_in_network}<small>vehicles</small></strong></div><div><span>QUEUED</span><strong>{f.movements.reduce((n,m)=>n+m.queue_veh,0)}<small>vehicles</small></strong></div><div><span>COMPLETED TRIPS</span><strong>{f.arrived_total}<small>of {f.inserted_total} inserted</small></strong></div><div><span>SEED</span><strong>{f.seed}<small>repeatable demand</small></strong></div></div><div className="signal-strip">{f.signals.map(s=><div key={s.node_id}><span className={`signal-light ${s.indication}`} /><strong>{s.node_id}</strong><span>{s.phase_id} · {s.indication.replace('_',' ')}</span><b>{s.remaining_s}s</b></div>)}</div><p className="field-hint">Run {f.run_id} · Source: {f.source} · Updated {new Date(f.timestamp).toLocaleTimeString()}</p></> : <p className="field-hint">Measurements are hidden until a fresh simulation frame arrives. Start or reset a scenario to establish a repeatable baseline.</p>}
 </section>
}
export function JunctionLive({frame,network,nodeID}:{frame:TrafficState|null;network:Network;nodeID:string}){
 const signal=frame?.signals.find(s=>s.node_id===nodeID);
 const movements=frame?.movements.filter(m=>network.movements.some(c=>c.id===m.movement_id&&c.node_id===nodeID));
 return <section className="junction-live"><h3>Current synthetic traffic</h3>{!frame ? <p>Live measurements unavailable or stale.</p> : <>{signal && <p className="current-signal"><span className={`signal-light ${signal.indication}`}/>{signal.phase_id} · {signal.indication.replace('_',' ')} · {signal.remaining_s}s remaining</p>}{movements?.length ? <><p className="field-hint">Rates are raw arrivals/departures over the last 1s interval, expressed per minute.</p>{movements.map(m=><div className="movement-live" key={m.movement_id}><div><strong>{m.movement_id}</strong><span className={`permission ${m.permission}`}>{m.permission}</span></div><dl><div><dt>Queue</dt><dd>{m.queue_veh} veh</dd></div><div><dt>Speed</dt><dd>{m.avg_speed_kph.toFixed(1)} km/h</dd></div><div><dt>Arrivals / departures</dt><dd>{m.arrival_rate_vpm} / {m.departure_rate_vpm} vpm</dd></div><div><dt>Incoming occupancy</dt><dd>{Math.round(m.occupancy_ratio*100)}%</dd></div><div><dt>Downstream space</dt><dd>{m.downstream_capacity_veh} veh</dd></div><div><dt>Longest wait</dt><dd>{m.waiting_age_s.toFixed(0)}s</dd></div></dl></div>)}</> : <p className="field-hint">Boundary node: no controlled movements.</p>}</>}</section>
}
