"""Generate TypeScript and JSON schema from the checked-in protobuf descriptor."""
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path('packages/contracts/gen/python').resolve()))
import twin_pb2 as pb
from google.protobuf.descriptor import FieldDescriptor as F
messages=pb.DESCRIPTOR.message_types_by_name
schemas={};interfaces=[]
for name,message in messages.items():
    props={};fields=[]
    for f in message.fields:
        if f.type==F.TYPE_MESSAGE:
            schema={'$ref':f'#/$defs/{f.message_type.name}'};typ=f.message_type.name
        elif f.type==F.TYPE_STRING:
            schema={'type':'string'};typ='string'
        elif f.type==F.TYPE_BOOL:
            schema={'type':'boolean'};typ='boolean'
        elif f.type==F.TYPE_UINT64:
            schema={'type':'string','pattern':'^[0-9]+$'};typ='string'
        else:
            schema={'type':'number' if f.type in (F.TYPE_DOUBLE,F.TYPE_FLOAT) else 'integer'};typ='number'
            if f.type in (F.TYPE_UINT32,F.TYPE_UINT64):schema['minimum']=0
        if f.is_repeated:
            schema={'type':'array','items':schema};typ=f'{typ}[]'
        # Aggregate v1.1 fields are additive. Old replay JSON and UI fixtures
        # remain valid while new producers publish the richer state.
        compatibility_optional = (name == 'TrafficState' and f.number >= 18) or (name == 'ComparisonResult' and f.number >= 15)
        optional=f.containing_oneof is not None or f.type==F.TYPE_MESSAGE and not f.is_repeated or compatibility_optional
        if f.type==F.TYPE_MESSAGE and not f.is_repeated:
            schema={"anyOf":[schema,{"type":"null"}]};typ+=" | null"
        if not optional and schema.get('type') in ('number','integer') and (f.name.endswith(('_s','_veh','_vpm','_kph')) or f.name=='occupancy_ratio'):schema['minimum']=0
        if f.name=='occupancy_ratio':schema['maximum']=1
        if f.name=='schema_version' and name=='TrafficState':schema={'enum':['1.0','1.1']};typ='"1.0" | "1.1"'
        elif f.name=='schema_version':schema={'const':'1.0'};typ='"1.0"'
        props[f.name]=schema;fields.append(f'  {f.name}{"?" if optional else ""}: {typ};')
    schemas[name]={'type':'object','properties':props,'additionalProperties':False,'required':[f.name for f in message.fields if f.containing_oneof is None and not (f.type==F.TYPE_MESSAGE and not f.is_repeated) and not ((name == 'TrafficState' and f.number >= 18) or (name == 'ComparisonResult' and f.number >= 15))]}
    interfaces.append(f'export interface {name} {{\n'+ '\n'.join(fields)+'\n}')
# JSON events use the PRD names, with discriminated payloads. Protobuf uses a oneof.
events={'network.state':'TrafficState','junction.state':'SignalState','forecast.updated':'Forecast','recommendation.created':'Recommendation','recommendation.updated':'Recommendation','incident.updated':'Incident','emergency.updated':'EmergencyEvent','health.updated':'HealthState','audit.appended':'AuditEvent'}
variants=[];types=[]
for event,model in events.items():
    variants.append({'type':'object','additionalProperties':False,'required':['schema_version','sequence','timestamp','type','payload'],'properties':{'schema_version':{'const':'1.0'},'sequence':{'type':'string','pattern':'^[0-9]+$'},'timestamp':{'type':'string','format':'date-time'},'type':{'const':event},'payload':{'$ref':f'#/$defs/{model}'}}})
    types.append(f'{{ schema_version: "1.0"; sequence: string; timestamp: string; type: "{event}"; payload: {model} }}')
Path('packages/contracts/typescript/events.ts').write_text('// Generated by scripts/generate_contract_docs.py; do not edit.\n'+'\n\n'.join(interfaces)+'\n\nexport type LiveEvent =\n  '+' |\n  '.join(types)+';\n')
Path('packages/contracts/events.schema.json').write_text(json.dumps({'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'urn:traffic:v1:events','oneOf':variants,'$defs':schemas},indent=2)+'\n')
